# Generated by Django 5.2.8 on 2025-11-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
