# Generated by Django 5.2.8 on 2025-11-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mystudent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('second_name', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('email', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['first_name'],
            },
        ),
    ]
